spring:
  main:
    allow-bean-definition-overriding: true
    web-application-type: NONE
  batch:
    initialize-schema: never
    job:
     # enabled: false
      names: ${job.name:NONE}
  profiles:
    include: local

logging:
  level:
    ROOT: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace


